author: Daniel Scalzi
description: Utility plugin that can compress files and extract archives.
main: com.dscalzi.zipextractor.ZipExtractor
name: ZipExtractor
version: 1.2.0
commands:
    zipextractor:
        description: Accesses plugin commands.
        usage: /ZipExtractor
        aliases: [ze]
permissions:
    zipextractor.harmless.notify:
        description: User will be notified if the plugin broadcasts a message.
    zipextractor.admin.use:
        description: Allow usage of /ZipExtractor
    zipextractor.admin.extract:
        description: Allow usage of /ZipExtractor extract
    zipextractor.admin.compress:
        description: Allow usage of /ZipExtractor compress
    zipextractor.admin.override.extract:
        description: Allow usage of /ZipExtractor extract -override
    zipextractor.admin.override.compress:
        description: Allow usage of /ZipExtractor compress -override
    zipextractor.admin.src:
        description: Allow usage of /ZipExtractor src
    zipextractor.admin.dest:
        description: Allow usage of /ZipExtractor dest
    zipextractor.admin.setsrc:
        description: Allow usage of /ZipExtractor setsrc
    zipextractor.admin.setdest:
        description: Allow usage of /ZipExtractor setdest
    zipextractor.harmless.status:
        description: Allow usage of /ZipExtractor status
    zipextractor.admin.plugindir:
        description: Allow usage of /ZipExtractor plugindir
    zipextractor.admin.terminate:
        description: Allow usage of /ZipExtractor terminate
    zipextractor.admin.forceterminate:
        description: Allow usage of /ZipExtractor forceterminate
    zipextractor.admin.reload:
        description: Allow usage of /ZipExtractor reload
    zipextractor.admin.*:
        default: OP
        description: Access to administrator commands.
        children:
          zipextractor.harmless.notify: true
          zipextractor.admin.use: true
          zipextractor.admin.extract: true
          zipextractor.admin.compress: true
          zipextractor.admin.override.extract: true
          zipextractor.admin.override.compress: true
          zipextractor.admin.src: true
          zipextractor.admin.dest: true
          zipextractor.admin.setsrc: true
          zipextractor.admin.setdest: true
          zipextractor.harmless.status: true
          zipextractor.admin.plugindir: true
          zipextractor.admin.terminate: true
          zipextractor.admin.forceterminate: true
          zipextractor.admin.reload: true