#
# This file is part of ZipExtractor.
# Copyright (C) 2016-2018 Daniel D. Scalzi <https://github.com/dscalzi/ZipExtractor>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

author: Daniel Scalzi
description: Utility plugin to extract archives and compress files.
main: com.dscalzi.zipextractor.bukkit.ZipExtractor
name: ZipExtractor
version: 2.0.0
api-version: 1.13
commands:
    zipextractor:
        description: Accesses plugin commands.
        usage: /ZipExtractor
        aliases: [ze]
permissions:
    zipextractor.harmless.notify:
        description: User will be notified if the plugin broadcasts a message.
    zipextractor.admin.use:
        description: Allow usage of /ZipExtractor
    zipextractor.admin.extract:
        description: Allow usage of /ZipExtractor extract
    zipextractor.admin.compress:
        description: Allow usage of /ZipExtractor compress
    zipextractor.admin.override.extract:
        description: Allow usage of /ZipExtractor extract -override
    zipextractor.admin.override.compress:
        description: Allow usage of /ZipExtractor compress -override
    zipextractor.admin.src:
        description: Allow usage of /ZipExtractor src
    zipextractor.admin.dest:
        description: Allow usage of /ZipExtractor dest
    zipextractor.admin.setsrc:
        description: Allow usage of /ZipExtractor setsrc
    zipextractor.admin.setdest:
        description: Allow usage of /ZipExtractor setdest
    zipextractor.harmless.status:
        description: Allow usage of /ZipExtractor status
    zipextractor.admin.plugindir:
        description: Allow usage of /ZipExtractor plugindir
    zipextractor.admin.terminate:
        description: Allow usage of /ZipExtractor terminate
    zipextractor.admin.forceterminate:
        description: Allow usage of /ZipExtractor forceterminate
    zipextractor.admin.reload:
        description: Allow usage of /ZipExtractor reload
    zipextractor.*:
        description: Full access to ZipExtractor.
        children:
            zipextractor.admin.*:
                description: Access to administrator commands.
                children:
                    zipextractor.admin.use: true
                    zipextractor.admin.extract: true
                    zipextractor.admin.compress: true
                    zipextractor.admin.override.extract: true
                    zipextractor.admin.override.compress: true
                    zipextractor.admin.src: true
                    zipextractor.admin.dest: true
                    zipextractor.admin.setsrc: true
                    zipextractor.admin.setdest: true
                    zipextractor.admin.plugindir: true
                    zipextractor.admin.terminate: true
                    zipextractor.admin.forceterminate: true
                    zipextractor.admin.reload: true
            zipextractor.harmless.*:
                description: Access to harmless commands.
                children:
                    zipextractor.harmless.notify: true
                    zipextractor.harmless.status: true
